# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e96251f6ab7810346c0a5442615fb355176e691ce4181c1a375d3f35df70d631ae22c15229e16d40b5b429a86c9060e72bcb9dd366cb39e9b402e0f796801666

test:
  secret_key_base: dac106e9b0c377eb7c7a282c14a3aa6657225a0fea0d109b4bc264281a562803f8e00150109ca12c8ac327d879465532d247b0d7e72e3838c92f190b21d3365f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
